services:
  
  server:
      image: nginx:latest
      restart: unless-stopped
      ports:
        - 8000:80      
      networks:
        - app-network
      volumes:
        - ./:/var/www/html
        - ./nginx.conf:/etc/nginx/nginx.conf
 
  db:
      image: postgres:latest  
      restart: always    
      ports:
        - 5433:5432   
      environment:
        POSTGRES_DB: laravel
        POSTGRES_USER: jersoft
        POSTGRES_PASSWORD: 3562987    
      networks:
        - app-network     

  app:
      build: .
      restart: unless-stopped      
      networks:
        - app-network
      volumes:
        - ./:/var/www/html  

networks:
  app-network:
    driver: bridge